### ISSUE TITLE
make a ArcToolbox wrapper for the osm2mapaction script

### ISSUE THREAD

**Issue by chrisewing** [mapaction/osm2mapaction#12]

**Comment by chrisewing** [comment]
I'm trying to work out how I do this.
My issue is that I can't simply modify the existing osm2mapaction.py script as I will need to pass to the script the python environment to use (i.e. C:\OSGeo4W64\OSGeo4W.bat).
So I think my plan is to create a new .py script which uses popen to call osm2mapaction.py.
Does it sounds sensible?

**Comment by andrewphilipsmith** [comment]
Completed by @harry-gibson  as part of this PR
https://github.com/mapaction/osm2mapaction/pull/35
